name: Proto linter

on:
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - 'proto/**'

permissions: {}

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required"'
